name: aptiotalent
description: "Une application d'offre d'emploi."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sizer: ^3.0.5
  google_fonts: ^6.2.1
  intl_phone_number_input:
    git:
      url: https://github.com/Shahidbangash/intl_phone_number_input.git
      ref: develop
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  gap: ^3.0.1
  http: ^1.2.2
  pinput: ^5.0.0
  syncfusion_flutter_gauges: ^27.2.4
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  awesome_snackbar_content: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
